# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('astistas', models.ManyToManyField(to='loja.Artista')),
            ],
        ),
    ]
