# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='artista',
            name='generos',
            field=models.ManyToManyField(to='loja.Genero'),
        ),
    ]
