# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_auto_20170329_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musicas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.Album')),
            ],
        ),
        migrations.AddField(
            model_name='artista',
            name='numero_gostei',
            field=models.IntegerField(default=0),
        ),
    ]
