# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_auto_20170329_1518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musicas',
            new_name='Musica',
        ),
    ]
