# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_auto_20170329_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='astistas',
            new_name='artistas',
        ),
    ]
